(function(){
  'use strict';
  const adapters=new Map();let open=false,mode='value',channel='x';
  const timelineArea=document.getElementById('timeline-area'),splitter=document.getElementById('timeline-graph-resize'),panel=document.getElementById('graph-editor'),toggle=document.getElementById('btn-graph-editor'),canvas=document.getElementById('graph-editor-canvas'),viewport=document.getElementById('graph-editor-viewport'),empty=document.getElementById('graph-editor-empty'),channelSelect=document.getElementById('graph-channel'),interpolationControls=document.getElementById('graph-interpolation-controls'),interpolationSelect=document.getElementById('graph-interpolation'),applyButton=document.getElementById('graph-apply-interpolation');
  const colors={x:'#ef6a72',y:'#66c58f',zoom:'#8579e6',rotation:'#e5b55f'},activeAdapter=()=>Array.from(adapters.values()).find(adapter=>adapter.isActive());
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  const cubic=(t,a,b)=>{const mt=1-t;return 3*mt*mt*t*a+3*mt*t*t*b+t*t*t;};
  const cubicDerivative=(t,a,b)=>{const mt=1-t;return 3*mt*mt*a+6*mt*t*(b-a)+3*t*t*(1-b);};
  function builtInControl(type){if(type==='ease')return{x1:1/3,y1:0,x2:2/3,y2:1};if(type==='ease-in')return{x1:1/3,y1:0,x2:2/3,y2:1/3};if(type==='ease-out')return{x1:1/3,y1:2/3,x2:2/3,y2:1};return{x1:1/3,y1:1/3,x2:2/3,y2:2/3};}
  function controlFor(key){const value=key&&key.interpolation==='bezier'&&key.bezier?key.bezier:builtInControl(key&&key.interpolation);return{x1:clamp(Number(value.x1)||0,.001,.999),y1:clamp(Number(value.y1)||0,-8,9),x2:clamp(Number(value.x2)||0,.001,.999),y2:clamp(Number(value.y2)||0,-8,9)};}
  function cubicTime(control,progress){let lo=0,hi=1,t=progress;for(let i=0;i<12;i++){const x=cubic(t,control.x1,control.x2);if(Math.abs(x-progress)<1e-5)break;if(x<progress)lo=t;else hi=t;t=(lo+hi)/2;}return t;}
  function cameraAdapter(){return{id:'camera',isActive:()=>!!(window.CameraTimeline&&CameraTimeline.selected&&window.CameraSystem&&CameraSystem.value.enabled),keys:()=>CameraSystem.value.track.keys,selectedFrames:()=>CameraTimeline.getSelectedFrames(),channels:{x:{label:'Position X',read:key=>key.x,write:(key,value)=>key.x=value},y:{label:'Position Y',read:key=>key.y,write:(key,value)=>key.y=value},zoom:{label:'Zoom',read:key=>key.zoom*100,write:(key,value)=>key.zoom=clamp(value/100,.1,16)},rotation:{label:'Rotation',read:key=>key.rotation,write:(key,value)=>key.rotation=((value+180)%360+360)%360-180,delta:(a,b)=>((b-a+540)%360)-180}},applyInterpolation:(frames,type)=>CameraSystem.setKeyInterpolation(frames,type),snapshot:()=>CameraSystem.trackSnapshot(),preview:keys=>{CameraSystem.replaceTrackKeys(keys);CameraSystem.evaluateAt(typeof curFrame==='number'?curFrame:0);},commit:before=>{CameraSystem.commitTrack(before,'graph-edit');CameraSystem.evaluateAt(typeof curFrame==='number'?curFrame:0);},restore:before=>CameraSystem.restoreTrack(before)};}
  function channelDelta(definition,a,b){const from=definition.read(a),to=definition.read(b);return definition.delta?definition.delta(from,to):to-from;}
  function segmentValue(a,b,definition,progress){if((a.interpolation||'linear')==='hold')return progress<1?definition.read(a):definition.read(b);const control=controlFor(a),t=cubicTime(control,progress);return definition.read(a)+channelDelta(definition,a,b)*cubic(t,control.y1,control.y2);}
  function segmentSpeed(a,b,definition,progress){if((a.interpolation||'linear')==='hold')return 0;const control=controlFor(a),t=cubicTime(control,progress),dx=Math.max(1e-5,cubicDerivative(t,control.x1,control.x2)),dy=cubicDerivative(t,control.y1,control.y2);return Math.abs(channelDelta(definition,a,b))/Math.max(1,b.frame-a.frame)*Math.max(0,dy/dx);}
  function graphSamples(keys,definition,width){const points=[];if(!keys.length||!definition)return points;if(keys.length===1)return[{frame:keys[0].frame,value:mode==='speed'?0:definition.read(keys[0])}];const span=Math.max(1,keys[keys.length-1].frame-keys[0].frame),pixelsPerFrame=Math.max(1,(width-28)/span);for(let index=0;index<keys.length-1;index++){const a=keys[index],b=keys[index+1],duration=Math.max(1,b.frame-a.frame),steps=Math.max(3,Math.min(240,Math.ceil(duration*pixelsPerFrame/3)));points.push({frame:a.frame,value:mode==='speed'?segmentSpeed(a,b,definition,0):definition.read(a)});if(mode==='value'&&a.interpolation==='hold'){points.push({frame:b.frame,value:definition.read(a)});points.push({frame:b.frame,value:definition.read(b)});continue;}for(let step=1;step<=steps;step++){const progress=step/steps;points.push({frame:a.frame+duration*progress,value:mode==='speed'?segmentSpeed(a,b,definition,progress):segmentValue(a,b,definition,progress)});}}return points;}
  function keyGraphValue(keys,definition,index){if(mode==='value')return definition.read(keys[index]);if(keys.length<2)return 0;const segment=Math.min(index,keys.length-2),progress=index===keys.length-1?1:0;return segmentSpeed(keys[segment],keys[segment+1],definition,progress);}
  let graphView=null,graphTargets=[],graphDrag=null,activeCurveFrame=null;
  function drawHandle(context,anchor,handle,target){context.strokeStyle='rgba(190,185,225,.72)';context.lineWidth=1;context.beginPath();context.moveTo(anchor.x,anchor.y);context.lineTo(handle.x,handle.y);context.stroke();context.fillStyle='#f0b52e';context.strokeStyle='rgba(20,18,30,.9)';context.beginPath();context.arc(handle.x,handle.y,4,0,Math.PI*2);context.fill();context.stroke();graphTargets.push(Object.assign({kind:'handle',x:handle.x,y:handle.y},target));}
  function draw(){
    if(!open||!viewport)return;
    const adapter=activeAdapter(),allKeys=adapter&&adapter.keys()||[],selected=adapter?adapter.selectedFrames():[],selectedIndices=allKeys.map((key,index)=>selected.includes(key.frame)?index:-1).filter(index=>index>=0),keys=selectedIndices.map(index=>allKeys[index]),selectionIsAdjacent=selectedIndices.every((index,position)=>position===0||index===selectedIndices[position-1]+1),rect=viewport.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1),width=Math.max(1,Math.round(rect.width)),height=Math.max(1,Math.round(rect.height));canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);
    const context=canvas.getContext('2d'),styles=getComputedStyle(document.documentElement),gridColor=styles.getPropertyValue('--border').trim()||'rgba(155,150,185,.16)';context.setTransform(dpr,0,0,dpr,0,0);context.clearRect(0,0,width,height);context.lineWidth=1;context.strokeStyle=gridColor;context.globalAlpha=.55;
    for(let i=1;i<5;i++){const y=Math.round(height*i/5)+.5;context.beginPath();context.moveTo(0,y);context.lineTo(width,y);context.stroke();}for(let i=1;i<9;i++){const x=Math.round(width*i/9)+.5;context.beginPath();context.moveTo(x,0);context.lineTo(x,height);context.stroke();}context.globalAlpha=1;graphTargets=[];
    if(!adapter||!adapter.channels[channel]||selected.length===0){empty.textContent='No selected keyframes';empty.hidden=false;interpolationControls.hidden=true;graphView=null;return;}if(keys.length<2){empty.textContent='Select at least 2 keyframes';empty.hidden=false;interpolationControls.hidden=true;graphView=null;return;}if(!selectionIsAdjacent){empty.textContent='Selected keyframes must be adjacent';empty.hidden=false;interpolationControls.hidden=true;graphView=null;return;}empty.hidden=true;
    const definition=adapter.channels[channel];interpolationControls.hidden=false;if(selected.length){const activeIndex=keys.findIndex(key=>key.frame===activeCurveFrame),activeKey=activeIndex>=0&&selected.some(frame=>frame===keys[activeIndex].frame||activeIndex+1<keys.length&&frame===keys[activeIndex+1].frame)?keys[activeIndex]:null;if(activeKey)interpolationSelect.value=activeKey.interpolation||'linear';else{const selectedKeys=keys.filter(key=>selected.includes(key.frame)),types=new Set(selectedKeys.map(key=>key.interpolation||'linear'));if(types.size===1)interpolationSelect.value=selectedKeys[0].interpolation||'linear';}}
    const points=graphSamples(keys,definition,width),values=points.map(point=>point.value),rawMin=Math.min(...values),rawMax=Math.max(...values),rawRange=rawMax-rawMin,margin=rawRange>1e-6?rawRange*.12:Math.max(1,Math.abs(rawMax)*.1),locked=graphDrag&&graphDrag.view,minimum=locked?locked.minimum:(mode==='speed'?0:rawMin-margin),maximum=locked?locked.maximum:rawMax+margin,range=Math.max(.0001,maximum-minimum),padding=14,first=locked?locked.first:keys[0].frame,last=locked?locked.last:Math.max(keys[0].frame+1,keys[keys.length-1].frame),xAt=frame=>padding+(frame-first)/(last-first)*(width-padding*2),yAt=value=>height-padding-(value-minimum)/range*(height-padding*2),frameAt=x=>first+(x-padding)/(width-padding*2)*(last-first),valueAt=y=>minimum+(height-padding-y)/(height-padding*2)*range;graphView={minimum,maximum,first,last,width,height,padding,xAt,yAt,frameAt,valueAt};
    if(mode==='speed'){const zeroY=Math.round(yAt(0))+.5;context.strokeStyle=gridColor;context.globalAlpha=.9;context.beginPath();context.moveTo(0,zeroY);context.lineTo(width,zeroY);context.stroke();context.globalAlpha=1;}
    context.strokeStyle=colors[channel]||'#8579e6';context.lineWidth=2;context.lineJoin='round';context.lineCap='round';context.beginPath();points.forEach((point,index)=>{const x=xAt(point.frame),y=yAt(point.value);if(index)context.lineTo(x,y);else context.moveTo(x,y);});context.stroke();
    keys.forEach((key,index)=>{const selectedKey=selected.includes(key.frame),x=xAt(key.frame),y=yAt(keyGraphValue(keys,definition,index));context.fillStyle=selectedKey?'#f7f5ff':colors[channel]||'#8579e6';context.strokeStyle=selectedKey?'#8579e6':'rgba(8,8,14,.8)';context.lineWidth=1;context.beginPath();context.rect(Math.round(x)-4+.5,Math.round(y)-4+.5,7,7);context.fill();context.stroke();graphTargets.push({kind:'key',index:allKeys.indexOf(key),curveIndex:index,x,y});});
    for(let index=0;index<keys.length-1;index++){const a=keys[index],b=keys[index+1];if(!selected.includes(a.frame)&&!selected.includes(b.frame)||a.interpolation==='hold')continue;const control=controlFor(a),duration=b.frame-a.frame,delta=channelDelta(definition,a,b),base=Math.abs(delta)/Math.max(1,duration),startSpeed=base*control.y1/control.x1,endSpeed=base*(1-control.y2)/(1-control.x2),aPoint={x:xAt(a.frame),y:yAt(mode==='speed'?startSpeed:definition.read(a))},bPoint={x:xAt(b.frame),y:yAt(mode==='speed'?endSpeed:definition.read(b))},segmentPixels=Math.abs(bPoint.x-aPoint.x),speedSpan=Math.max(24,segmentPixels*.5),outPoint={x:mode==='speed'?aPoint.x+speedSpan*control.x1:xAt(a.frame+duration*control.x1),y:yAt(mode==='speed'?startSpeed:definition.read(a)+delta*control.y1)},inPoint={x:mode==='speed'?bPoint.x-speedSpan*(1-control.x2):xAt(a.frame+duration*control.x2),y:yAt(mode==='speed'?endSpeed:definition.read(a)+delta*control.y2)};const aIndex=allKeys.indexOf(a),bIndex=allKeys.indexOf(b);drawHandle(context,aPoint,outPoint,{segment:index,aIndex,bIndex,side:'out',anchorX:aPoint.x,speedSpan});drawHandle(context,bPoint,inPoint,{segment:index,aIndex,bIndex,side:'in',anchorX:bPoint.x,speedSpan});}
    const playheadX=xAt(typeof curFrame==='number'?curFrame:0);context.strokeStyle='rgba(239,83,91,.9)';context.lineWidth=1;context.beginPath();context.moveTo(Math.round(playheadX)+.5,0);context.lineTo(Math.round(playheadX)+.5,height);context.stroke();
  }
  function graphPoint(event){const rect=canvas.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};}
  function hitGraph(point){let best=null,bestDistance=10;for(const target of graphTargets){const distance=Math.hypot(point.x-target.x,point.y-target.y);if(distance<bestDistance){best=target;bestDistance=distance;}}return best;}
  function beginGraphDrag(event){if(event.button!==0||!graphView)return;const adapter=activeAdapter(),target=hitGraph(graphPoint(event));if(!adapter||!target)return;if(target.kind==='handle')activeCurveFrame=adapter.keys()[target.aIndex].frame;event.preventDefault();event.stopPropagation();graphDrag={pointerId:event.pointerId,target,before:adapter.snapshot(),keys:adapter.keys().map(key=>JSON.parse(JSON.stringify(key))),curveIndices:adapter.keys().map((key,index)=>adapter.selectedFrames().includes(key.frame)?index:-1).filter(index=>index>=0),adapter,view:Object.assign({},graphView)};canvas.setPointerCapture(event.pointerId);canvas.classList.add('graph-dragging');}
  function setKeySpeed(keys,index,speed,definition){if(index<keys.length-1){const a=keys[index],b=keys[index+1],control=controlFor(a),base=Math.abs(channelDelta(definition,a,b))/Math.max(1,b.frame-a.frame);control.y1=base<1e-6?0:clamp(speed/base*control.x1,-8,9);a.interpolation='bezier';a.bezier=control;}if(index>0){const a=keys[index-1],b=keys[index],control=controlFor(a),base=Math.abs(channelDelta(definition,a,b))/Math.max(1,b.frame-a.frame),influence=1-control.x2;control.y2=base<1e-6?1:1-clamp(speed/base*influence,-8,9);a.interpolation='bezier';a.bezier=control;}}
  function updateGraphDrag(event){if(!graphDrag||event.pointerId!==graphDrag.pointerId)return;event.preventDefault();const point=graphPoint(event),view=graphDrag.view,keys=graphDrag.keys,definition=graphDrag.adapter.channels[channel],target=graphDrag.target;if(target.kind==='key'){if(mode==='speed'){const curveKeys=graphDrag.curveIndices.map(index=>keys[index]);setKeySpeed(curveKeys,target.curveIndex,Math.max(0,view.valueAt(point.y)),definition);}else definition.write(keys[target.index],view.valueAt(point.y));}else{const a=keys[target.aIndex],b=keys[target.bIndex],duration=Math.max(1,b.frame-a.frame),control=controlFor(a),normalizedX=mode==='speed'?(target.side==='out'?clamp((point.x-target.anchorX)/target.speedSpan,.001,.999):1-clamp((target.anchorX-point.x)/target.speedSpan,.001,.999)):clamp((view.frameAt(point.x)-a.frame)/duration,.001,.999),delta=channelDelta(definition,a,b);if(target.side==='out'){control.x1=normalizedX;if(mode==='value')control.y1=Math.abs(delta)<1e-6?.5:clamp((view.valueAt(point.y)-definition.read(a))/delta,-8,9);else{const base=Math.abs(delta)/duration,speed=Math.max(0,view.valueAt(point.y));control.y1=base<1e-6?0:clamp(speed/base*control.x1,-8,9);}}else{control.x2=normalizedX;if(mode==='value')control.y2=Math.abs(delta)<1e-6?.5:clamp((view.valueAt(point.y)-definition.read(a))/delta,-8,9);else{const base=Math.abs(delta)/duration,speed=Math.max(0,view.valueAt(point.y)),influence=1-control.x2;control.y2=base<1e-6?1:1-clamp(speed/base*influence,-8,9);}}a.interpolation='bezier';a.bezier=control;}graphDrag.adapter.preview(keys);draw();}
  function finishGraphDrag(event,cancelled){if(!graphDrag||event.pointerId!==graphDrag.pointerId)return;event.preventDefault();const drag=graphDrag;graphDrag=null;canvas.classList.remove('graph-dragging');try{if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);}catch(_){}if(cancelled)drag.adapter.restore(drag.before);else drag.adapter.commit(drag.before);draw();}
  canvas.addEventListener('pointerdown',beginGraphDrag);canvas.addEventListener('pointermove',event=>{if(graphDrag)updateGraphDrag(event);else canvas.style.cursor=hitGraph(graphPoint(event))?'pointer':'default';});canvas.addEventListener('pointerup',event=>finishGraphDrag(event,false));canvas.addEventListener('pointercancel',event=>finishGraphDrag(event,true));canvas.addEventListener('lostpointercapture',event=>{if(graphDrag&&event.pointerId===graphDrag.pointerId)finishGraphDrag(event,true);});  let splitRatio=.5,splitPointerId=null;
  function syncSplit(){if(!open)return;const width=timelineArea.getBoundingClientRect().width,divider=splitter.offsetWidth||6,min=Math.min(280,Math.max(140,(width-divider)*.25)),left=Math.max(min,Math.min(width-divider-min,(width-divider)*splitRatio));timelineArea.style.setProperty('--timeline-pane-width',left+'px');requestAnimationFrame(draw);}
  function setOpen(value){open=!!value;panel.hidden=!open;splitter.hidden=!open;timelineArea.classList.toggle('graph-editor-open',open);toggle.classList.toggle('active',open);toggle.setAttribute('aria-pressed',String(open));if(open)requestAnimationFrame(()=>{syncSplit();draw();});}
  splitter.addEventListener('pointerdown',event=>{if(event.button!==0&&event.pointerType!=='pen')return;splitPointerId=event.pointerId;splitter.classList.add('dragging');splitter.setPointerCapture(event.pointerId);event.preventDefault();event.stopPropagation();});
  splitter.addEventListener('pointermove',event=>{if(event.pointerId!==splitPointerId)return;const rect=timelineArea.getBoundingClientRect(),divider=splitter.offsetWidth||6;splitRatio=Math.max(0,Math.min(1,(event.clientX-rect.left)/(rect.width-divider)));syncSplit();event.preventDefault();});
  function endSplit(event){if(event.pointerId!==splitPointerId)return;splitPointerId=null;splitter.classList.remove('dragging');if(splitter.hasPointerCapture(event.pointerId))splitter.releasePointerCapture(event.pointerId);}
  splitter.addEventListener('pointerup',endSplit);splitter.addEventListener('pointercancel',endSplit);splitter.addEventListener('lostpointercapture',event=>{if(event.pointerId===splitPointerId){splitPointerId=null;splitter.classList.remove('dragging');}});
  toggle.onclick=()=>setOpen(!open);document.querySelectorAll('.graph-mode-btn').forEach(button=>button.onclick=()=>{mode=button.dataset.graphMode;document.querySelectorAll('.graph-mode-btn').forEach(item=>item.classList.toggle('active',item===button));draw();});channelSelect.onchange=()=>{channel=channelSelect.value;draw();};applyButton.onclick=()=>{const adapter=activeAdapter(),frames=adapter&&adapter.selectedFrames();if(adapter&&frames.length){adapter.applyInterpolation(frames,interpolationSelect.value);draw();}};
  window.addEventListener('timeline-rendered',draw);window.addEventListener('camera-changed',draw);window.addEventListener('project-loaded',draw);window.addEventListener('resize',()=>{syncSplit();draw();});if(window.ResizeObserver)new ResizeObserver(draw).observe(viewport);adapters.set('camera',cameraAdapter());window.TimelineGraphEditor={registerAdapter(id,adapter){adapters.set(id,adapter);draw();},refresh:draw,get open(){return open;}};
})();