(function(){
  'use strict';
  const adapters=new Map();let open=false,mode='value',channel='x';
  const timelineArea=document.getElementById('timeline-area'),autoKeyButton=document.getElementById('btn-camera-auto-key'),panel=document.getElementById('graph-editor'),toggle=document.getElementById('btn-graph-editor'),canvas=document.getElementById('graph-editor-canvas'),viewport=document.getElementById('graph-editor-viewport'),empty=document.getElementById('graph-editor-empty'),channelSelect=document.getElementById('graph-channel'),interpolationControls=document.getElementById('graph-interpolation-controls'),interpolationSelect=document.getElementById('graph-interpolation'),applyButton=document.getElementById('graph-apply-interpolation');
  const colors={x:'#ef6a72',y:'#66c58f',zoom:'#8579e6',rotation:'#e5b55f'},ease=(type,t)=>type==='hold'?0:type==='ease'?t*t*(3-2*t):type==='ease-in'?t*t:type==='ease-out'?1-(1-t)*(1-t):t,activeAdapter=()=>Array.from(adapters.values()).find(adapter=>adapter.isActive());
  function cameraAdapter(){return{id:'camera',isActive:()=>!!(window.CameraTimeline&&CameraTimeline.selected&&window.CameraSystem),keys:()=>CameraSystem.value.track.keys,selectedFrames:()=>CameraTimeline.getSelectedFrames(),channels:{x:{label:'Position X',read:key=>key.x},y:{label:'Position Y',read:key=>key.y},zoom:{label:'Zoom',read:key=>key.zoom*100},rotation:{label:'Rotation',read:key=>key.rotation}},applyInterpolation:(frames,type)=>CameraSystem.setKeyInterpolation(frames,type)};}
  function evaluate(keys,read,frame){if(!keys.length)return 0;const exact=keys.find(key=>key.frame===frame);if(exact)return read(exact);if(frame<=keys[0].frame)return read(keys[0]);if(frame>=keys[keys.length-1].frame)return read(keys[keys.length-1]);let right=1;while(right<keys.length&&keys[right].frame<frame)right++;const a=keys[right-1],b=keys[right],t=ease(a.interpolation||'linear',(frame-a.frame)/(b.frame-a.frame));if(channel==='rotation'){const delta=((read(b)-read(a)+540)%360)-180;return read(a)+delta*t;}return read(a)+(read(b)-read(a))*t;}
  function samples(adapter,width){const keys=adapter.keys(),read=adapter.channels[channel].read,first=keys[0].frame,last=keys[keys.length-1].frame,count=Math.max(2,Math.min(width*2,(last-first+1)*8)),values=[];for(let i=0;i<count;i++){const frame=first+(last-first)*(i/(count-1)),value=evaluate(keys,read,frame);values.push({frame,value});}if(mode==='speed')for(let i=0;i<values.length;i++){const previous=values[Math.max(0,i-1)],next=values[Math.min(values.length-1,i+1)],distance=Math.max(.0001,next.frame-previous.frame);values[i]={frame:values[i].frame,value:Math.abs(next.value-previous.value)/distance};}return values;}
  function draw(){if(!open||!viewport)return;const adapter=activeAdapter(),keys=adapter&&adapter.keys()||[],rect=viewport.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1),width=Math.max(1,Math.round(rect.width)),height=Math.max(1,Math.round(rect.height));canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);const context=canvas.getContext('2d');context.setTransform(dpr,0,0,dpr,0,0);context.clearRect(0,0,width,height);context.strokeStyle='rgba(155,150,185,.16)';context.lineWidth=1;for(let i=1;i<4;i++){const y=Math.round(height*i/4)+.5;context.beginPath();context.moveTo(0,y);context.lineTo(width,y);context.stroke();}if(!adapter||keys.length<1||!adapter.channels[channel]){empty.hidden=false;interpolationControls.hidden=true;return;}empty.hidden=true;const selected=adapter.selectedFrames();interpolationControls.hidden=!selected.length;if(selected.length){const selectedKeys=keys.filter(key=>selected.includes(key.frame)),types=new Set(selectedKeys.map(key=>key.interpolation||'linear'));if(types.size===1)interpolationSelect.value=selectedKeys[0].interpolation||'linear';}const points=samples(adapter,width),allValues=points.map(point=>point.value),minimum=Math.min(...allValues),maximum=Math.max(...allValues),range=Math.max(.0001,maximum-minimum),padding=14,first=keys[0].frame,last=Math.max(first+1,keys[keys.length-1].frame),xAt=frame=>padding+(frame-first)/(last-first)*(width-padding*2),yAt=value=>height-padding-(value-minimum)/range*(height-padding*2);context.strokeStyle=colors[channel];context.lineWidth=1.5;context.beginPath();points.forEach((point,index)=>{const x=xAt(point.frame),y=yAt(point.value);if(index)context.lineTo(x,y);else context.moveTo(x,y);});context.stroke();if(mode==='value')keys.forEach(key=>{const selectedKey=selected.includes(key.frame),x=xAt(key.frame),y=yAt(adapter.channels[channel].read(key));context.fillStyle=selectedKey?'#f7f5ff':colors[channel];context.strokeStyle=selectedKey?'#8579e6':'rgba(8,8,14,.8)';context.beginPath();context.rect(x-3.5,y-3.5,7,7);context.fill();context.stroke();});const playheadX=xAt(typeof curFrame==='number'?curFrame:0);context.strokeStyle='rgba(239,83,91,.8)';context.beginPath();context.moveTo(Math.round(playheadX)+.5,0);context.lineTo(Math.round(playheadX)+.5,height);context.stroke();}
  function setOpen(value){open=!!value;panel.hidden=!open;timelineArea.classList.toggle('graph-editor-open',open);toggle.classList.toggle('active',open);toggle.setAttribute('aria-pressed',String(open));if(open)requestAnimationFrame(draw);}
  function syncAutoKey(){const enabled=!!(window.CameraSystem&&CameraSystem.autoKey);autoKeyButton.classList.toggle('auto-key-on',enabled);autoKeyButton.setAttribute('aria-pressed',String(enabled));}
  autoKeyButton.onclick=()=>{if(window.CameraSystem)CameraSystem.setAutoKey(!CameraSystem.autoKey);syncAutoKey();};syncAutoKey();
  toggle.onclick=()=>setOpen(!open);document.querySelectorAll('.graph-mode-btn').forEach(button=>button.onclick=()=>{mode=button.dataset.graphMode;document.querySelectorAll('.graph-mode-btn').forEach(item=>item.classList.toggle('active',item===button));draw();});channelSelect.onchange=()=>{channel=channelSelect.value;draw();};applyButton.onclick=()=>{const adapter=activeAdapter(),frames=adapter&&adapter.selectedFrames();if(adapter&&frames.length){adapter.applyInterpolation(frames,interpolationSelect.value);draw();}};
  window.addEventListener('timeline-rendered',draw);window.addEventListener('camera-changed',draw);window.addEventListener('project-loaded',draw);window.addEventListener('resize',draw);if(window.ResizeObserver)new ResizeObserver(draw).observe(viewport);adapters.set('camera',cameraAdapter());window.TimelineGraphEditor={registerAdapter(id,adapter){adapters.set(id,adapter);draw();},refresh:draw,get open(){return open;}};
})();