(function(){
  'use strict';
  const MIN_ZOOM=0.1,MAX_ZOOM=16,HANDLE_SIZE=8;
  let camera=null,overlay=null,active=false,gesture=null;
  const finite=(value,fallback)=>value!==null&&value!==''&&Number.isFinite(Number(value))?Number(value):fallback;
  const angle=value=>{let n=finite(value,0)%360;if(n>180)n-=360;if(n<=-180)n+=360;return n;};
  function defaultCamera(){return{enabled:true,positionX:0,positionY:0,zoom:1,rotation:0,track:{keys:[]},settingsTab:'basic',output:{preset:'custom',width:CW,height:CH},view:{shade:28,frameOpacity:100},guides:{showFrame:true,showCenter:true,showThirds:false,showSafeArea:false,outer:5,inner:10}};}
  function normalize(value){const fallback=defaultCamera(),source=value&&typeof value==='object'?value:{},output=source.output&&typeof source.output==='object'?source.output:{},view=source.view&&typeof source.view==='object'?source.view:{},guides=source.guides&&typeof source.guides==='object'?source.guides:{},rawKeys=source.track&&Array.isArray(source.track.keys)?source.track.keys:[],keyMap=new Map();rawKeys.forEach(item=>{const frame=Math.max(0,Math.round(finite(item&&item.frame,0)));keyMap.set(frame,{frame,x:finite(item&&item.x,0),y:finite(item&&item.y,0),zoom:Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,finite(item&&item.zoom,1)>0?finite(item.zoom,1):1)),rotation:angle(item&&item.rotation)});});const track={keys:Array.from(keyMap.values()).sort((a,b)=>a.frame-b.frame)},preset=['custom','hd720','hd1080','2k','4k','square','vertical'].includes(output.preset)?output.preset:'custom',width=Math.round(Math.max(1,Math.min(16384,finite(output.width,fallback.output.width)))),height=Math.round(Math.max(1,Math.min(16384,finite(output.height,fallback.output.height))));return{enabled:source.enabled!==false,positionX:finite(source.positionX,fallback.positionX),positionY:finite(source.positionY,fallback.positionY),zoom:Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,finite(source.zoom,fallback.zoom)>0?finite(source.zoom,fallback.zoom):1)),rotation:angle(source.rotation),track,settingsTab:source.settingsTab==='advanced'?'advanced':'basic',output:{preset,width,height},view:{shade:Math.max(0,Math.min(100,finite(view.shade,fallback.view.shade))),frameOpacity:Math.max(0,Math.min(100,finite(view.frameOpacity,fallback.view.frameOpacity)))},guides:{showFrame:guides.showFrame!==false,showCenter:guides.showCenter!==false,showThirds:!!guides.showThirds,showSafeArea:!!guides.showSafeArea,outer:Math.max(0,Math.min(50,finite(guides.outer,fallback.guides.outer))),inner:Math.max(0,Math.min(50,finite(guides.inner,fallback.guides.inner)))}};}
  function snapshot(){return JSON.parse(JSON.stringify(camera));}
  function transformSnapshot(value){value=value||camera;return{x:value.positionX,y:value.positionY,zoom:value.zoom,rotation:value.rotation};}
  function evaluateTrack(frame){
    const keys=camera.track.keys;if(!keys.length)return snapshot();frame=Math.max(0,Math.round(finite(frame,0)));
    let value;if(frame<=keys[0].frame)value=keys[0];else if(frame>=keys[keys.length-1].frame)value=keys[keys.length-1];else{let right=1;while(right<keys.length&&keys[right].frame<frame)right++;const a=keys[right-1],b=keys[right],t=(frame-a.frame)/(b.frame-a.frame),delta=((b.rotation-a.rotation+540)%360)-180;value={x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,zoom:a.zoom+(b.zoom-a.zoom)*t,rotation:angle(a.rotation+delta*t)};}
    camera.positionX=value.x;camera.positionY=value.y;camera.zoom=value.zoom;camera.rotation=angle(value.rotation);notify(true);return snapshot();
  }
  function trackSnapshot(){return JSON.parse(JSON.stringify(camera.track));}
  function restoreTrack(value,frame){camera.track=normalize(Object.assign({},camera,{track:value})).track;if(camera.track.keys.length)evaluateTrack(frame==null?(typeof curFrame==='number'?curFrame:0):frame);else notify(false);return trackSnapshot();}
  function commitTrack(before,type){const after=trackSnapshot();if(before&&JSON.stringify(before)!==JSON.stringify(after)){undoStack.push({type:'camera-track',operation:type||'edit',before:JSON.parse(JSON.stringify(before)),after});if(undoStack.length>40)undoStack.shift();redoStack.length=0;}notify(false);if(typeof renderTimeline==='function')renderTimeline();return after;}
  function addOrUpdateKey(frame){frame=Math.max(0,Math.min(typeof TOTAL==='number'?TOTAL-1:Number.MAX_SAFE_INTEGER,Math.round(finite(frame,0))));const before=trackSnapshot(),value=transformSnapshot(),key={frame,x:value.x,y:value.y,zoom:value.zoom,rotation:value.rotation},index=camera.track.keys.findIndex(item=>item.frame===frame);if(index>=0)camera.track.keys[index]=key;else camera.track.keys.push(key);camera.track.keys.sort((a,b)=>a.frame-b.frame);commitTrack(before,index>=0?'update':'add');return key;}
  function deleteKeys(frames){const selected=new Set((frames||[]).map(Number)),before=trackSnapshot();camera.track.keys=camera.track.keys.filter(key=>!selected.has(key.frame));commitTrack(before,'delete');if(camera.track.keys.length)evaluateTrack(typeof curFrame==='number'?curFrame:0);return trackSnapshot();}
  function replaceTrackKeys(keys,operation,before){camera.track=normalize(Object.assign({},camera,{track:{keys}})).track;if(before)commitTrack(before,operation);else notify(true);return trackSnapshot();}
  function same(a,b){return JSON.stringify(a)===JSON.stringify(b);}
  function cameraCenter(value){value=value||camera;return{x:CW/2+value.positionX,y:CH/2+value.positionY};}
  function getCameraMatrix(value){value=value||camera;const center=cameraCenter(value),matrix=new DOMMatrix();matrix.translateSelf(CW/2,CH/2);matrix.rotateSelf(-value.rotation);matrix.scaleSelf(value.zoom,value.zoom);matrix.translateSelf(-center.x,-center.y);return matrix;}
  function worldToCamera(point,value){const p=new DOMPoint(point.x,point.y).matrixTransform(getCameraMatrix(value));return{x:p.x,y:p.y};}
  function cameraToWorld(point,value){const p=new DOMPoint(point.x,point.y).matrixTransform(getCameraMatrix(value).inverse());return{x:p.x,y:p.y};}
  function getCameraWorldBounds(value){value=value||camera;const center=cameraCenter(value),halfW=value.output.width/(2*value.zoom),halfH=value.output.height/(2*value.zoom),r=value.rotation*Math.PI/180,cos=Math.cos(r),sin=Math.sin(r);return[[-halfW,-halfH],[halfW,-halfH],[halfW,halfH],[-halfW,halfH]].map(([x,y])=>({x:center.x+x*cos-y*sin,y:center.y+x*sin+y*cos}));}
  function screenGeometry(value){const world=getCameraWorldBounds(value),points=world.map(EditorOverlayRenderer.worldToScreen),center=EditorOverlayRenderer.worldToScreen(cameraCenter(value));return{world,points,center};}
  function drawDimmedOutside(ctx,points,width,height,opacity){if(opacity<=0)return;ctx.save();ctx.fillStyle='rgba(5,5,10,'+opacity+')';ctx.beginPath();ctx.rect(0,0,width,height);ctx.moveTo(points[0].x,points[0].y);for(let i=3;i>=0;i--)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();ctx.fill('evenodd');ctx.restore();}
  function path(ctx,points){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();}
  function guideLine(ctx,a,b){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
  function hasVisibleGuide(value){const guides=value&&value.guides;return !!(guides&&(guides.showFrame||guides.showCenter||guides.showThirds||guides.showSafeArea));}
  function drawOverlay(ctx,geometry){
    if(!camera.enabled||!hasVisibleGuide(camera))return;
    const display=screenGeometry(camera),points=display.points,frameOpacity=camera.view.frameOpacity/100;
    if(camera.guides.showFrame)drawDimmedOutside(ctx,points,geometry.width,geometry.height,camera.view.shade/100);
    const mix=(a,b,t)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});
    ctx.save();ctx.lineWidth=1;ctx.strokeStyle='rgba(132,122,255,.98)';ctx.globalAlpha=frameOpacity;ctx.setLineDash([6,4]);if(camera.guides.showFrame){path(ctx,points);ctx.stroke();}ctx.setLineDash([]);ctx.globalAlpha=frameOpacity*.75;
    if(camera.guides.showThirds){for(const t of [1/3,2/3]){guideLine(ctx,mix(points[0],points[1],t),mix(points[3],points[2],t));guideLine(ctx,mix(points[0],points[3],t),mix(points[1],points[2],t));}}
    if(camera.guides.showSafeArea){for(const margin of [camera.guides.outer,camera.guides.inner]){const t=margin/50,safe=[mix(points[0],display.center,t),mix(points[1],display.center,t),mix(points[2],display.center,t),mix(points[3],display.center,t)];path(ctx,safe);ctx.stroke();}}
    if(camera.guides.showCenter){ctx.strokeStyle='#f0b52e';guideLine(ctx,{x:display.center.x-7,y:display.center.y},{x:display.center.x+7,y:display.center.y});guideLine(ctx,{x:display.center.x,y:display.center.y-7},{x:display.center.x,y:display.center.y+7});}
    ctx.globalAlpha=1;if(active&&camera.guides.showFrame){ctx.strokeStyle='rgba(132,122,255,.98)';for(const point of points){ctx.fillStyle='#f8f7ff';ctx.fillRect(point.x-HANDLE_SIZE/2,point.y-HANDLE_SIZE/2,HANDLE_SIZE,HANDLE_SIZE);ctx.strokeRect(point.x-HANDLE_SIZE/2,point.y-HANDLE_SIZE/2,HANDLE_SIZE,HANDLE_SIZE);}}ctx.restore();
  }
  function pointerScreen(event){const rect=canvasArea.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};}
  function hitTest(event){const point=getPos(event),display=screenGeometry(camera),center=cameraCenter(camera),hit=typeof _tfHitTestGeneric==='function'?_tfHitTestGeneric(point,display.world,camera.rotation,1/camera.zoom,center,camera.output.width,camera.output.height,null):null;if(!hit)return null;return{kind:hit.mode==='scale'?'zoom':hit.mode,point:pointerScreen(event),display,transformHit:hit};}
  function notify(live){if(overlay){overlay.canvas.style.pointerEvents=active?'auto':'none';overlay.setVisible(active||hasVisibleGuide(camera));overlay.invalidate();}window.dispatchEvent(new CustomEvent('camera-changed',{detail:{camera:snapshot(),live:!!live}}));}
  function begin(event){if(!active||event.isPrimary===false||((event.pointerType==='mouse'||event.pointerType==='pen')&&event.button!==0))return;const hit=hitTest(event);if(!hit)return;event.preventDefault();event.stopPropagation();const initial=snapshot();gesture={pointerId:event.pointerId,kind:hit.kind,initial,startScreen:hit.point,startCenter:hit.display.center,startDistance:Math.max(1,Math.hypot(hit.point.x-hit.display.center.x,hit.point.y-hit.display.center.y)),startAngle:Math.atan2(hit.point.y-hit.display.center.y,hit.point.x-hit.display.center.x)};overlay.canvas.setPointerCapture(event.pointerId);document.body.classList.add('camera-interacting');}
  function update(event){if(!active){return;}if(!gesture){const hit=hitTest(event);overlay.canvas.style.cursor=hit&&typeof _tfHitCursor==='function'?_tfHitCursor(hit.transformHit):'default';return;}if(event.pointerId!==gesture.pointerId)return;event.preventDefault();const point=pointerScreen(event);if(gesture.kind==='move'){const rect=canvasArea.getBoundingClientRect(),startWorld=getPos({clientX:rect.left+gesture.startScreen.x,clientY:rect.top+gesture.startScreen.y}),world=getPos(event);camera.positionX=gesture.initial.positionX+world.x-startWorld.x;camera.positionY=gesture.initial.positionY+world.y-startWorld.y;}else if(gesture.kind==='zoom'){const distance=Math.max(1,Math.hypot(point.x-gesture.startCenter.x,point.y-gesture.startCenter.y));camera.zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,gesture.initial.zoom*gesture.startDistance/distance));}else{let delta=Math.atan2(point.y-gesture.startCenter.y,point.x-gesture.startCenter.x)-gesture.startAngle;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;camera.rotation=angle(gesture.initial.rotation+delta*180/Math.PI);}notify(true);}
  function finish(event,cancelled){if(!gesture||event.pointerId!==gesture.pointerId)return;event.preventDefault();const initial=gesture.initial;gesture=null;document.body.classList.remove('camera-interacting');try{if(overlay.canvas.hasPointerCapture(event.pointerId))overlay.canvas.releasePointerCapture(event.pointerId);}catch(_){}if(cancelled){camera=initial;notify(false);return;}if(!same(initial,camera)){undoStack.push({type:'camera-state',before:initial,after:snapshot()});if(undoStack.length>40)undoStack.shift();redoStack.length=0;}notify(false);}
  function enter(){active=true;notify(false);}
  function exit(){if(gesture){camera=gesture.initial;gesture=null;document.body.classList.remove('camera-interacting');}active=false;notify(false);}
  function renderScene(source,target){const context=target.getContext('2d'),matrix=getCameraMatrix(camera);context.save();context.setTransform(1,0,0,1,0,0);context.clearRect(0,0,target.width,target.height);context.setTransform(matrix.a,matrix.b,matrix.c,matrix.d,matrix.e,matrix.f);context.drawImage(source,0,0);context.restore();return target;}
  function cloneGuides(guides){return Object.assign({},guides);}
  function updateCamera(patch,live){const next=Object.assign({},camera,patch||{});for(const key of ['output','view','guides'])if(patch&&patch[key])next[key]=Object.assign({},camera[key],patch[key]);camera=normalize(next);notify(live);return snapshot();}
  function commit(before){if(before&&!same(before,camera)){undoStack.push({type:'camera-state',before:normalize(before),after:snapshot()});if(undoStack.length>40)undoStack.shift();redoStack.length=0;}notify(false);}
  function perform(patch){const before=snapshot();updateCamera(patch,true);commit(before);}
  function restore(value){camera=normalize(value);notify(false);return true;}
  function load(value){camera=normalize(value);if(camera.track.keys.length)evaluateTrack(typeof curFrame==='number'?curFrame:0);else notify(false);return true;}
  function reset(withHistory){const before=snapshot();if(withHistory){camera=Object.assign(defaultCamera(),{track:trackSnapshot(),settingsTab:camera.settingsTab,output:Object.assign({},camera.output),view:Object.assign({},camera.view),guides:cloneGuides(camera.guides)});commit(before);}else{camera=defaultCamera();notify(false);}}
  const OUTPUT_PRESETS={hd720:[1280,720],hd1080:[1920,1080],'2k':[2048,1080],'4k':[3840,2160],square:[1080,1080],vertical:[1080,1920]};
  function init(){camera=defaultCamera();overlay=EditorOverlayRenderer.create('camera-overlay',{zIndex:7,pointerEvents:'auto',draw:drawOverlay});overlay.canvas.addEventListener('pointerdown',begin);overlay.canvas.addEventListener('pointermove',update);overlay.canvas.addEventListener('pointerup',event=>finish(event,false));overlay.canvas.addEventListener('pointercancel',event=>finish(event,true));overlay.canvas.addEventListener('lostpointercapture',event=>{if(gesture&&event.pointerId===gesture.pointerId)finish(event,true);});window.addEventListener('canvas-view-transform-changed',()=>overlay.invalidate());}
  window.CameraSystem={init,enter,exit,reset,restore,load,serialize:snapshot,snapshot,getCameraMatrix,worldToCamera,cameraToWorld,getCameraWorldBounds,renderScene,update:updateCamera,commit,perform,evaluateAt:evaluateTrack,trackSnapshot,restoreTrack,commitTrack,replaceTrackKeys,addOrUpdateKey,deleteKeys,resetWithHistory(){reset(true);},get outputPresets(){return JSON.parse(JSON.stringify(OUTPUT_PRESETS));},get value(){return snapshot();},get active(){return active;}};
  document.addEventListener('DOMContentLoaded',init);
})();
