(function(){
  'use strict';
  const MIN_ZOOM=0.1,MAX_ZOOM=16,HANDLE_SIZE=8;
  let camera=null,overlay=null,active=false,gesture=null;
  const finite=(value,fallback)=>value!==null&&value!==''&&Number.isFinite(Number(value))?Number(value):fallback;
  const angle=value=>{let n=finite(value,0)%360;if(n>180)n-=360;if(n<=-180)n+=360;return n;};
  function defaultCamera(){return{enabled:true,positionX:0,positionY:0,zoom:1,rotation:0,guides:{showFrame:true,showCenter:true,showThirds:false,showSafeArea:false}};}
  function normalize(value){const fallback=defaultCamera(),source=value&&typeof value==='object'?value:{},guides=source.guides&&typeof source.guides==='object'?source.guides:{};return{enabled:source.enabled!==false,positionX:finite(source.positionX,fallback.positionX),positionY:finite(source.positionY,fallback.positionY),zoom:Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,finite(source.zoom,fallback.zoom)>0?finite(source.zoom,fallback.zoom):1)),rotation:angle(source.rotation),guides:{showFrame:guides.showFrame!==false,showCenter:guides.showCenter!==false,showThirds:!!guides.showThirds,showSafeArea:!!guides.showSafeArea}};}
  function snapshot(){return JSON.parse(JSON.stringify(camera));}
  function same(a,b){return JSON.stringify(a)===JSON.stringify(b);}
  function cameraCenter(value){value=value||camera;return{x:CW/2+value.positionX,y:CH/2+value.positionY};}
  function getCameraMatrix(value){value=value||camera;const center=cameraCenter(value),matrix=new DOMMatrix();matrix.translateSelf(CW/2,CH/2);matrix.rotateSelf(-value.rotation);matrix.scaleSelf(value.zoom,value.zoom);matrix.translateSelf(-center.x,-center.y);return matrix;}
  function worldToCamera(point,value){const p=new DOMPoint(point.x,point.y).matrixTransform(getCameraMatrix(value));return{x:p.x,y:p.y};}
  function cameraToWorld(point,value){const p=new DOMPoint(point.x,point.y).matrixTransform(getCameraMatrix(value).inverse());return{x:p.x,y:p.y};}
  function getCameraWorldBounds(value){return[{x:0,y:0},{x:CW,y:0},{x:CW,y:CH},{x:0,y:CH}].map(point=>cameraToWorld(point,value));}
  function screenGeometry(value){const world=getCameraWorldBounds(value),points=world.map(EditorOverlayRenderer.worldToScreen),center=EditorOverlayRenderer.worldToScreen(cameraCenter(value));return{world,points,center};}
  function drawDimmedOutside(ctx,points,width,height){ctx.save();ctx.fillStyle='rgba(5,5,10,.28)';ctx.beginPath();ctx.rect(0,0,width,height);ctx.moveTo(points[0].x,points[0].y);for(let i=3;i>=0;i--)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();ctx.fill('evenodd');ctx.restore();}
  function path(ctx,points){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();}
  function guideLine(ctx,a,b){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
  function drawOverlay(ctx,geometry){if(!camera.enabled||(!active&&!camera.guides.showFrame))return;const display=screenGeometry(camera),points=display.points;if(active)drawDimmedOutside(ctx,points,geometry.width,geometry.height);ctx.save();ctx.lineWidth=1;ctx.strokeStyle='rgba(132,122,255,.98)';ctx.setLineDash([6,4]);path(ctx,points);ctx.stroke();ctx.setLineDash([]);
    const mix=(a,b,t)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});ctx.globalAlpha=.55;
    if(camera.guides.showThirds){for(const t of [1/3,2/3]){guideLine(ctx,mix(points[0],points[1],t),mix(points[3],points[2],t));guideLine(ctx,mix(points[0],points[3],t),mix(points[1],points[2],t));}}
    if(camera.guides.showSafeArea){const safe=[mix(points[0],display.center,.1),mix(points[1],display.center,.1),mix(points[2],display.center,.1),mix(points[3],display.center,.1)];path(ctx,safe);ctx.stroke();}
    if(camera.guides.showCenter){ctx.strokeStyle='#f0b52e';guideLine(ctx,{x:display.center.x-7,y:display.center.y},{x:display.center.x+7,y:display.center.y});guideLine(ctx,{x:display.center.x,y:display.center.y-7},{x:display.center.x,y:display.center.y+7});}
    ctx.globalAlpha=1;if(active){ctx.strokeStyle='rgba(132,122,255,.98)';for(const point of points){ctx.fillStyle='#f8f7ff';ctx.fillRect(point.x-HANDLE_SIZE/2,point.y-HANDLE_SIZE/2,HANDLE_SIZE,HANDLE_SIZE);ctx.strokeRect(point.x-HANDLE_SIZE/2,point.y-HANDLE_SIZE/2,HANDLE_SIZE,HANDLE_SIZE);}}ctx.restore();}
  function pointerScreen(event){const rect=canvasArea.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};}
  function hitTest(event){const point=getPos(event),display=screenGeometry(camera),center=cameraCenter(camera),hit=typeof _tfHitTestGeneric==='function'?_tfHitTestGeneric(point,display.world,camera.rotation,1/camera.zoom,center,CW,CH,null):null;if(!hit)return null;return{kind:hit.mode==='scale'?'zoom':hit.mode,point:pointerScreen(event),display,transformHit:hit};}
  function notify(live){if(overlay){overlay.canvas.style.pointerEvents=active?'auto':'none';overlay.setVisible(active||!!(camera&&camera.guides&&camera.guides.showFrame));overlay.invalidate();}window.dispatchEvent(new CustomEvent('camera-changed',{detail:{camera:snapshot(),live:!!live}}));}
  function begin(event){if(!active||event.isPrimary===false||((event.pointerType==='mouse'||event.pointerType==='pen')&&event.button!==0))return;const hit=hitTest(event);if(!hit)return;event.preventDefault();event.stopPropagation();const initial=snapshot();gesture={pointerId:event.pointerId,kind:hit.kind,initial,startScreen:hit.point,startCenter:hit.display.center,startDistance:Math.max(1,Math.hypot(hit.point.x-hit.display.center.x,hit.point.y-hit.display.center.y)),startAngle:Math.atan2(hit.point.y-hit.display.center.y,hit.point.x-hit.display.center.x)};overlay.canvas.setPointerCapture(event.pointerId);document.body.classList.add('camera-interacting');}
  function update(event){if(!active){return;}if(!gesture){const hit=hitTest(event);overlay.canvas.style.cursor=hit&&typeof _tfHitCursor==='function'?_tfHitCursor(hit.transformHit):'default';return;}if(event.pointerId!==gesture.pointerId)return;event.preventDefault();const point=pointerScreen(event);if(gesture.kind==='move'){const rect=canvasArea.getBoundingClientRect(),startWorld=getPos({clientX:rect.left+gesture.startScreen.x,clientY:rect.top+gesture.startScreen.y}),world=getPos(event);camera.positionX=gesture.initial.positionX+world.x-startWorld.x;camera.positionY=gesture.initial.positionY+world.y-startWorld.y;}else if(gesture.kind==='zoom'){const distance=Math.max(1,Math.hypot(point.x-gesture.startCenter.x,point.y-gesture.startCenter.y));camera.zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,gesture.initial.zoom*gesture.startDistance/distance));}else{let delta=Math.atan2(point.y-gesture.startCenter.y,point.x-gesture.startCenter.x)-gesture.startAngle;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;camera.rotation=angle(gesture.initial.rotation+delta*180/Math.PI);}notify(true);}
  function finish(event,cancelled){if(!gesture||event.pointerId!==gesture.pointerId)return;event.preventDefault();const initial=gesture.initial;gesture=null;document.body.classList.remove('camera-interacting');try{if(overlay.canvas.hasPointerCapture(event.pointerId))overlay.canvas.releasePointerCapture(event.pointerId);}catch(_){}if(cancelled){camera=initial;notify(false);return;}if(!same(initial,camera)){undoStack.push({type:'camera-state',before:initial,after:snapshot()});if(undoStack.length>40)undoStack.shift();redoStack.length=0;}notify(false);}
  function enter(){active=true;notify(false);}
  function exit(){if(gesture){camera=gesture.initial;gesture=null;document.body.classList.remove('camera-interacting');}active=false;notify(false);}
  function renderScene(source,target){const context=target.getContext('2d'),matrix=getCameraMatrix(camera);context.save();context.setTransform(1,0,0,1,0,0);context.clearRect(0,0,target.width,target.height);context.setTransform(matrix.a,matrix.b,matrix.c,matrix.d,matrix.e,matrix.f);context.drawImage(source,0,0);context.restore();return target;}
  function cloneGuides(guides){return Object.assign({},guides);}
  function updateCamera(patch,live){const next=Object.assign({},camera,patch||{});if(patch&&patch.guides)next.guides=Object.assign({},camera.guides,patch.guides);camera=normalize(next);notify(live);return snapshot();}
  function commit(before){if(before&&!same(before,camera)){undoStack.push({type:'camera-state',before:normalize(before),after:snapshot()});if(undoStack.length>40)undoStack.shift();redoStack.length=0;}notify(false);}
  function perform(patch){const before=snapshot();updateCamera(patch,true);commit(before);}
  function restore(value){camera=normalize(value);notify(false);return true;}
  function reset(withHistory){const before=snapshot(),guides=withHistory?cloneGuides(camera.guides):defaultCamera().guides;camera=Object.assign(defaultCamera(),{guides});if(withHistory)commit(before);else notify(false);}
  function init(){camera=defaultCamera();overlay=EditorOverlayRenderer.create('camera-overlay',{zIndex:7,pointerEvents:'auto',draw:drawOverlay});overlay.canvas.addEventListener('pointerdown',begin);overlay.canvas.addEventListener('pointermove',update);overlay.canvas.addEventListener('pointerup',event=>finish(event,false));overlay.canvas.addEventListener('pointercancel',event=>finish(event,true));overlay.canvas.addEventListener('lostpointercapture',event=>{if(gesture&&event.pointerId===gesture.pointerId)finish(event,true);});window.addEventListener('canvas-view-transform-changed',()=>overlay.invalidate());}
  window.CameraSystem={init,enter,exit,reset,restore,load:restore,serialize:snapshot,snapshot,getCameraMatrix,worldToCamera,cameraToWorld,getCameraWorldBounds,renderScene,update:updateCamera,commit,perform,resetWithHistory(){reset(true);},get value(){return snapshot();},get active(){return active;}};
  document.addEventListener('DOMContentLoaded',init);
})();
