// src/core/platform-input.js
//
// Platform and input device classification for context menu policy and pen handling.
//
// Separates:
// A. Desktop environment + pen/mouse/keyboard
// B. Tablet / mobile environment + pen/touch
//
// Policy:
// - Mouse right-click: allowed everywhere.
// - Keyboard shortcut (F2 / penContextMenu): allowed everywhere (dispatches synthetic contextmenu with isSynthesizedKeybind=true).
// - Pen barrel / secondary button click (e.buttons & 2 or button === 2 without long hold): allowed.
// - Tablet/mobile touch/pen long-press: allowed.
// - Desktop stylus long-press: suppressed / disabled.

'use strict';

(function (root) {
  // Track active/recent pointerdown contacts to identify whether a contextmenu event
  // was generated by holding a stylus tip down on desktop.
  let _lastDownPointerType = null;
  let _lastDownButton = 0;
  let _lastDownButtons = 0;
  let _lastDownTime = 0;

  /**
   * Records pointerdown state to assist in contextmenu event classification.
   * @param {PointerEvent|object} e
   */
  function recordPointerDown(e) {
    if (!e) return;
    _lastDownPointerType = e.pointerType || null;
    _lastDownButton = typeof e.button === 'number' ? e.button : 0;
    _lastDownButtons = typeof e.buttons === 'number' ? e.buttons : 0;
    _lastDownTime = (typeof performance !== 'undefined' && performance.now) ? performance.now() : Date.now();
  }

  /**
   * Resets recorded pointer state.
   */
  function resetPointerDown() {
    _lastDownPointerType = null;
    _lastDownButton = 0;
    _lastDownButtons = 0;
    _lastDownTime = 0;
  }

  /**
   * Checks whether the current runtime environment is a tablet or mobile device.
   * Desktop PCs (Windows, macOS, Linux, ChromeOS laptops) return false.
   * Android tablets/phones, iPads, iPhones, and touch-first mobile devices return true.
   *
   * @param {object} [env] Optional environment mocks for testing
   * @returns {boolean}
   */
  function isTabletOrMobileDevice(env) {
    const nav = env && env.navigator ? env.navigator : (typeof navigator !== 'undefined' ? navigator : null);
    const win = env && env.window ? env.window : (typeof window !== 'undefined' ? window : null);

    if (!nav) return false;

    const ua = (nav.userAgent || '') + ' ' + (nav.vendor || '');
    const platform = nav.platform || '';

    // Android tablet / phone
    if (/Android/i.test(ua)) return true;

    // iPad / iPhone / iPod (including iOS 13+ iPad reporting as MacIntel/Macintosh with multi-touch)
    if (/iPad|iPhone|iPod/i.test(ua) || /iPad|iPhone|iPod/i.test(platform)) return true;
    if (/Mac/i.test(platform) && nav.maxTouchPoints && nav.maxTouchPoints > 1) {
      // iPadOS reports as MacIntel with touch support
      return true;
    }

    // Windows Phone or other mobile UAs
    if (/Mobile|Tablet|Silk|Kindle/i.test(ua)) return true;

    // Check pointer media query if window.matchMedia is available
    if (win && typeof win.matchMedia === 'function') {
      const coarsePointer = win.matchMedia('(pointer: coarse)').matches;
      const noHover = win.matchMedia('(hover: none)').matches;
      const isDesktopPlatform = /Win|Mac|Linux|X11/i.test(platform) && !/Android|iPad|iPhone/i.test(platform);

      // A pure mobile/tablet touch device has coarse pointer and no hover
      if (coarsePointer && noHover && !isDesktopPlatform) {
        return true;
      }
    }

    return false;
  }

  /**
   * Evaluates whether a contextmenu event should be allowed based on platform and input source.
   *
   * @param {MouseEvent|PointerEvent|object} event - The contextmenu event
   * @param {object} [options]
   * @param {boolean} [options.isTabletMobile] - Override for platform classification
   * @param {string} [options.lastPointerType] - Override for recent pointerType
   * @param {number} [options.lastButton] - Override for recent pointerdown button
   * @param {number} [options.lastButtons] - Override for recent pointerdown buttons
   * @returns {boolean} true if context menu is permitted, false if suppressed
   */
  function shouldAllowContextMenu(event, options) {
    if (!event) return false;

    // 1. Explicit synthetic keyboard keybind (F2 / penContextMenu) is always allowed
    if (event._isKeybind || event.isSynthesizedKeybind) {
      return true;
    }

    // 2. Determine if running on mobile/tablet or desktop
    const isTabletMobile = (options && typeof options.isTabletMobile === 'boolean')
      ? options.isTabletMobile
      : isTabletOrMobileDevice(options && options.env);

    // Tablet/mobile environments permit all native context menus (including stylus & touch long-press)
    if (isTabletMobile) {
      return true;
    }

    // 3. Desktop environment:
    const pointerType = (event.pointerType) ||
      (options && options.lastPointerType !== undefined ? options.lastPointerType : _lastDownPointerType);
    const lastBtn = (options && options.lastButton !== undefined) ? options.lastButton : _lastDownButton;
    const lastBtns = (options && options.lastButtons !== undefined) ? options.lastButtons : _lastDownButtons;

    // Check if the current/originating pointer is a pen
    const isPen = pointerType === 'pen';

    if (isPen) {
      // Intentional pen secondary/barrel button click:
      // On Windows / Wacom, physical barrel button click sends secondary button 2 and buttons & 2.
      // Press-and-hold stylus tip starts with primary contact (button 0, buttons 1) and later emits synthetic contextmenu.
      const isBarrelClick = (lastBtns & 2) !== 0 || lastBtn === 2 || (event.buttons & 2) !== 0 || event.button === 2;
      const isTipHold = (lastBtns & 1) !== 0 || lastBtn === 0;

      // If it started as a primary tip hold on desktop (or is not a barrel click), suppress desktop hold contextmenu!
      if (isTipHold && !((lastBtns & 2) !== 0)) {
        return false;
      }
      if (!isBarrelClick) {
        return false;
      }
    }

    // Mouse right-click or other desktop inputs
    return true;
  }

  // Install global capturing contextmenu listener in browser environment.
  // This intercepts ANY contextmenu event before it reaches sub-element listeners.
  // If desktop stylus hold is detected, it immediately cancels and stops propagation
  // so NO app context menu or component popup can be opened.
  if (typeof window !== 'undefined' && typeof document !== 'undefined') {
    document.addEventListener('contextmenu', function (e) {
      if (!shouldAllowContextMenu(e)) {
        e.preventDefault();
        e.stopPropagation();
        if (typeof e.stopImmediatePropagation === 'function') {
          e.stopImmediatePropagation();
        }
      }
    }, true); // Use capturing phase to protect all elements globally
  }

  const PlatformInputExports = {
    recordPointerDown,
    resetPointerDown,
    isTabletOrMobileDevice,
    shouldAllowContextMenu,
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = PlatformInputExports;
  }
  if (typeof window !== 'undefined') {
    window.PlatformInput = PlatformInputExports;
  }
})(typeof globalThis !== 'undefined' ? globalThis : this);
